### ISSUE TITLE
Integrate `Cryptiiiic/ipwndfu:main`

### ISSUE THREAD

**Issue by nyuszika7h** [hack-different/ipwndfu#10]
Branch ~~`A11-patch-rom`~~ `main`. Based on akayn's fork for A11 (T8015), but with better sigcheck patch that doesn't require a reset (`irecovery -f junk.txt`) before sending iBEC/iBSS.

**Comment by Cryptiiiic** [comment]
@nyuszika7h moved to Cryptiiiic/ipwndfu_old -> main
