### ISSUE TITLE
iBoot Serial Number string parser to object

### ISSUE THREAD

**Issue by rickmark** [hack-different/ipwndfu#16]
Parse out the serial number into a tuple

**Comment by cxnder** [comment]
https://github.com/hack-different/ipwndfu/blob/master/ipwndfu#L587

**Comment by rickmark** [comment]
Worth considering: https://docs.python.org/3/library/dataclasses.html

**Comment by cxnder** [comment]
TIL that's a thing

But it wouldn't work in this case.

**Comment by rickmark** [comment]
Current is good enough
