### ISSUE TITLE
[Feature]: Support t7001 (A8X - iPad Air 2)

### ISSUE THREAD

**Issue by TheRealClarity** [hack-different/ipwndfu#63]
### Brief Description

T7001 is currently unsupported for no apparent reason.

### I'm building this

- [X] I volenteer to own this feature

**Comment by rickmark** [comment]
lol ^^ "hello YOUR NAME HERE"

will fix that

is there a branch with this working or?

**Comment by TheRealClarity** [comment]
Currently waiting for my tester 
[6a078b](https://github.com/hack-different/ipwndfu/commit/6a078bdc33445b2c896aed0fefea39581b18f493)
